#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

# BE SURE TO UPDATE THIS TO A PATH WHERE YOU HAVE SDL INSTALLED
SDL_LOCATION = C:\\SDL2
SDL_MIXER_LOCATION = C:\\SDL2
SDL_IMAGE_LOCATION = C:\\SDL2

INC = -I${SDL_LOCATION}\\include\\SDL2 -Iinclude
CFLAGS = 
RESINC = 
LIBDIR = -L${SDL_LOCATION}\\lib -L${SDL_IMAGE_LOCATION}\\lib -L${SDL_MIXER_LOCATION}\\lib
LIB = ${SDL_LOCATION}\\lib
LDFLAGS = -lmingw32 -lSDL2main -lSDL2 -lSDL2_mixer -lSDL2_image

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -w -Wl,-subsystem,windows
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = 
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\debug
DEP_DEBUG = 
OUT_DEBUG = bin\\debug\\test-emscripten.exe

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = 
OBJDIR_RELEASE = obj\\release
DEP_RELEASE = 
OUT_RELEASE = bin\\release\\test-emscripten.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\src\\thing.o $(OBJDIR_DEBUG)\\src\\main.o

OBJ_RELEASE = $(OBJDIR_DEBUG)\\src\\thing.o $(OBJDIR_RELEASE)\\src\\main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist $(OBJDIR_DEBUG)\\src md $(OBJDIR_DEBUG)\\src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)


$(OBJDIR_DEBUG)\\src\\thing.o: src\\thing.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\thing.cpp -o $(OBJDIR_DEBUG)\\src\\thing.o

$(OBJDIR_DEBUG)\\src\\main.o: src\\main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\main.cpp -o $(OBJDIR_DEBUG)\\src\\main.o


clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\debug
	cmd /c rd $(OBJDIR_DEBUG)\\src


before_release: 
	cmd /c if not exist bin\\release md bin\\release
	cmd /c if not exist $(OBJDIR_RELEASE)\\src md $(OBJDIR_RELEASE)\\src


after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\src\\thing.o: src\\thing.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\thing.cpp -o $(OBJDIR_RELEASE)\\src\\thing.o

$(OBJDIR_RELEASE)\\src\\main.o: src\\main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\main.cpp -o $(OBJDIR_RELEASE)\\src\\main.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\release
	cmd /c rd $(OBJDIR_RELEASE)\\src


.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

