CC = emcc
EMFLAGS = -s WASM=1 -s USE_SDL=2 -s USE_SDL_MIXER=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS=png -O3 --preload-file assets
SOURCES = src\\thing.cpp src\\main.cpp

build: $(SOURCES)
	$(CC) $(EMFLAGS) $(SOURCES) -o web\\index.html